// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {define} from '../models';

export function CheckForUpdates():Promise<define.QueryResult>;

export function CheckForUpdatesSilently():Promise<define.QueryResult>;

export function ConfirmQuit():Promise<void>;

export function CountLines(arg1:string):Promise<number>;

export function DetectKind(arg1:string):Promise<string>;

export function DownloadUpdate():Promise<define.QueryResult>;

export function GetAppInfo():Promise<define.QueryResult>;

export function GetRoot():Promise<string>;

export function InstallUpdateAndRestart():Promise<define.QueryResult>;

export function ListDir(arg1:string):Promise<Array<define.DirEntry>>;

export function OpenDownloadedUpdateDirectory():Promise<define.QueryResult>;

export function OpenDownloadedUpdatePackage():Promise<define.QueryResult>;

export function OpenRoot(arg1:string):Promise<void>;

export function PickAndOpen(arg1:string):Promise<define.PickOpenResult>;

export function PickAndOpenFile():Promise<string>;

export function PickAndOpenFolder():Promise<string>;

export function PickAndSaveFile(arg1:string):Promise<string>;

export function ReadBytes(arg1:string):Promise<Array<number>>;

export function ReadMarkdownOutline(arg1:string):Promise<Array<define.MdHeading>>;

export function ReadSlice(arg1:string,arg2:number,arg3:number):Promise<define.TextSlice>;

export function ReadText(arg1:string):Promise<string>;

export function StatFile(arg1:string):Promise<define.FileInfo>;

export function WriteText(arg1:string,arg2:string):Promise<void>;
