// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates() {
  return window['go']['app']['App']['CheckForUpdates']();
}

export function CheckForUpdatesSilently() {
  return window['go']['app']['App']['CheckForUpdatesSilently']();
}

export function ConfirmQuit() {
  return window['go']['app']['App']['ConfirmQuit']();
}

export function CountLines(arg1) {
  return window['go']['app']['App']['CountLines'](arg1);
}

export function DetectKind(arg1) {
  return window['go']['app']['App']['DetectKind'](arg1);
}

export function DownloadUpdate() {
  return window['go']['app']['App']['DownloadUpdate']();
}

export function GetAppInfo() {
  return window['go']['app']['App']['GetAppInfo']();
}

export function GetRoot() {
  return window['go']['app']['App']['GetRoot']();
}

export function InstallUpdateAndRestart() {
  return window['go']['app']['App']['InstallUpdateAndRestart']();
}

export function ListDir(arg1) {
  return window['go']['app']['App']['ListDir'](arg1);
}

export function OpenDownloadedUpdateDirectory() {
  return window['go']['app']['App']['OpenDownloadedUpdateDirectory']();
}

export function OpenDownloadedUpdatePackage() {
  return window['go']['app']['App']['OpenDownloadedUpdatePackage']();
}

export function OpenRoot(arg1) {
  return window['go']['app']['App']['OpenRoot'](arg1);
}

export function PickAndOpen(arg1) {
  return window['go']['app']['App']['PickAndOpen'](arg1);
}

export function PickAndOpenFile() {
  return window['go']['app']['App']['PickAndOpenFile']();
}

export function PickAndOpenFolder() {
  return window['go']['app']['App']['PickAndOpenFolder']();
}

export function PickAndSaveFile(arg1) {
  return window['go']['app']['App']['PickAndSaveFile'](arg1);
}

export function ReadBytes(arg1) {
  return window['go']['app']['App']['ReadBytes'](arg1);
}

export function ReadMarkdownOutline(arg1) {
  return window['go']['app']['App']['ReadMarkdownOutline'](arg1);
}

export function ReadSlice(arg1, arg2, arg3) {
  return window['go']['app']['App']['ReadSlice'](arg1, arg2, arg3);
}

export function ReadText(arg1) {
  return window['go']['app']['App']['ReadText'](arg1);
}

export function StatFile(arg1) {
  return window['go']['app']['App']['StatFile'](arg1);
}

export function WriteText(arg1, arg2) {
  return window['go']['app']['App']['WriteText'](arg1, arg2);
}
