// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRoot(arg1) {
  return window['go']['app']['App']['AddRoot'](arg1);
}

export function CheckForUpdates() {
  return window['go']['app']['App']['CheckForUpdates']();
}

export function CheckForUpdatesSilently() {
  return window['go']['app']['App']['CheckForUpdatesSilently']();
}

export function ConfirmQuit() {
  return window['go']['app']['App']['ConfirmQuit']();
}

export function CountLines(arg1) {
  return window['go']['app']['App']['CountLines'](arg1);
}

export function DetectKind(arg1) {
  return window['go']['app']['App']['DetectKind'](arg1);
}

export function DownloadUpdate() {
  return window['go']['app']['App']['DownloadUpdate']();
}

export function GetAppInfo() {
  return window['go']['app']['App']['GetAppInfo']();
}

export function GetGlobalProxyConfig() {
  return window['go']['app']['App']['GetGlobalProxyConfig']();
}

export function GetLaunchInfo() {
  return window['go']['app']['App']['GetLaunchInfo']();
}

export function GetOpenPlacementPrefs() {
  return window['go']['app']['App']['GetOpenPlacementPrefs']();
}

export function GetRoot() {
  return window['go']['app']['App']['GetRoot']();
}

export function GetRoots() {
  return window['go']['app']['App']['GetRoots']();
}

export function InstallUpdateAndRestart() {
  return window['go']['app']['App']['InstallUpdateAndRestart']();
}

export function ListDir(arg1) {
  return window['go']['app']['App']['ListDir'](arg1);
}

export function ListWindowsToRestore() {
  return window['go']['app']['App']['ListWindowsToRestore']();
}

export function LoadWindowSession(arg1) {
  return window['go']['app']['App']['LoadWindowSession'](arg1);
}

export function OpenDownloadedUpdateDirectory() {
  return window['go']['app']['App']['OpenDownloadedUpdateDirectory']();
}

export function OpenDownloadedUpdatePackage() {
  return window['go']['app']['App']['OpenDownloadedUpdatePackage']();
}

export function OpenRoot(arg1) {
  return window['go']['app']['App']['OpenRoot'](arg1);
}

export function PickAndOpen(arg1) {
  return window['go']['app']['App']['PickAndOpen'](arg1);
}

export function PickAndOpenFile() {
  return window['go']['app']['App']['PickAndOpenFile']();
}

export function PickAndOpenFolder() {
  return window['go']['app']['App']['PickAndOpenFolder']();
}

export function PickAndSaveFile(arg1) {
  return window['go']['app']['App']['PickAndSaveFile'](arg1);
}

export function ReadBytes(arg1) {
  return window['go']['app']['App']['ReadBytes'](arg1);
}

export function ReadMarkdownOutline(arg1) {
  return window['go']['app']['App']['ReadMarkdownOutline'](arg1);
}

export function ReadSlice(arg1, arg2, arg3) {
  return window['go']['app']['App']['ReadSlice'](arg1, arg2, arg3);
}

export function ReadText(arg1) {
  return window['go']['app']['App']['ReadText'](arg1);
}

export function RegisterWindow(arg1) {
  return window['go']['app']['App']['RegisterWindow'](arg1);
}

export function RemoveRoot(arg1) {
  return window['go']['app']['App']['RemoveRoot'](arg1);
}

export function SaveGlobalProxy(arg1) {
  return window['go']['app']['App']['SaveGlobalProxy'](arg1);
}

export function SaveOpenPlacementPrefs(arg1) {
  return window['go']['app']['App']['SaveOpenPlacementPrefs'](arg1);
}

export function SaveWindowSession(arg1) {
  return window['go']['app']['App']['SaveWindowSession'](arg1);
}

export function SetRoots(arg1) {
  return window['go']['app']['App']['SetRoots'](arg1);
}

export function SpawnNewWindow(arg1, arg2) {
  return window['go']['app']['App']['SpawnNewWindow'](arg1, arg2);
}

export function SpawnRestoredWindows() {
  return window['go']['app']['App']['SpawnRestoredWindows']();
}

export function StatFile(arg1) {
  return window['go']['app']['App']['StatFile'](arg1);
}

export function UnregisterWindow(arg1) {
  return window['go']['app']['App']['UnregisterWindow'](arg1);
}

export function WriteText(arg1, arg2) {
  return window['go']['app']['App']['WriteText'](arg1, arg2);
}
