// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {define} from '../models';
import {app} from '../models';

export function AddRoot(arg1:string):Promise<void>;

export function CheckForUpdates():Promise<define.QueryResult>;

export function CheckForUpdatesSilently():Promise<define.QueryResult>;

export function ConfirmQuit():Promise<void>;

export function CountLines(arg1:string):Promise<number>;

export function DetectKind(arg1:string):Promise<string>;

export function DownloadUpdate():Promise<define.QueryResult>;

export function GetAppInfo():Promise<define.QueryResult>;

export function GetGlobalProxyConfig():Promise<define.QueryResult>;

export function GetLaunchInfo():Promise<define.LaunchInfo>;

export function GetOpenPlacementPrefs():Promise<define.OpenPlacementPrefs>;

export function GetRoot():Promise<string>;

export function GetRoots():Promise<Array<string>>;

export function InstallUpdateAndRestart():Promise<define.QueryResult>;

export function InspectPath(arg1:string):Promise<define.PickOpenResult>;

export function ListDir(arg1:string):Promise<Array<define.DirEntry>>;

export function ListWindowsToRestore():Promise<Array<string>>;

export function LoadWindowSession(arg1:string):Promise<define.WindowSessionState>;

export function OpenDownloadedUpdateDirectory():Promise<define.QueryResult>;

export function OpenDownloadedUpdatePackage():Promise<define.QueryResult>;

export function OpenRoot(arg1:string):Promise<void>;

export function PickAndOpen(arg1:string):Promise<define.PickOpenResult>;

export function PickAndOpenFile():Promise<string>;

export function PickAndOpenFolder():Promise<string>;

export function PickAndSaveFile(arg1:string):Promise<string>;

export function ReadBytes(arg1:string):Promise<Array<number>>;

export function ReadMarkdownOutline(arg1:string):Promise<Array<define.MdHeading>>;

export function ReadSlice(arg1:string,arg2:number,arg3:number):Promise<define.TextSlice>;

export function ReadText(arg1:string):Promise<string>;

export function RegisterWindow(arg1:string):Promise<void>;

export function RemoveRoot(arg1:string):Promise<void>;

export function RevealInFileManager(arg1:string):Promise<void>;

export function SaveGlobalProxy(arg1:app.GlobalProxyView):Promise<define.QueryResult>;

export function SaveOpenPlacementPrefs(arg1:define.OpenPlacementPrefs):Promise<define.OpenPlacementPrefs>;

export function SaveWindowSession(arg1:define.WindowSessionState):Promise<void>;

export function SetRoots(arg1:Array<string>):Promise<void>;

export function SpawnNewWindow(arg1:string,arg2:boolean):Promise<string>;

export function SpawnRestoredWindows():Promise<void>;

export function StatFile(arg1:string):Promise<define.FileInfo>;

export function UnregisterWindow(arg1:string):Promise<void>;

export function WriteText(arg1:string,arg2:string):Promise<void>;
