import { isJsonFile } from './jsonFormat'

export function langFromPath(path: string, name = ''): string {
  const lower = path.toLowerCase()
  if (isJsonFile(path, name)) return 'json'
  if (lower.endsWith('.ts') || lower.endsWith('.tsx')) return 'typescript'
  if (lower.endsWith('.js') || lower.endsWith('.jsx') || lower.endsWith('.mjs') || lower.endsWith('.cjs')) return 'javascript'
  if (lower.endsWith('.go')) return 'go'
  if (lower.endsWith('.py')) return 'python'
  if (lower.endsWith('.yaml') || lower.endsWith('.yml')) return 'yaml'
  if (lower.endsWith('.toml')) return 'ini'
  if (lower.endsWith('.css') || lower.endsWith('.scss') || lower.endsWith('.less')) return 'css'
  if (lower.endsWith('.html') || lower.endsWith('.htm')) return 'html'
  if (lower.endsWith('.xml') || lower.endsWith('.plist')) return 'xml'
  if (lower.endsWith('.sql')) return 'sql'
  if (lower.endsWith('.sh') || lower.endsWith('.bash') || lower.endsWith('.zsh') || lower.endsWith('.fish')) return 'shell'
  if (lower.endsWith('.bat') || lower.endsWith('.cmd') || lower.endsWith('.ps1')) return 'powershell'
  if (lower.endsWith('.java') || lower.endsWith('.kt') || lower.endsWith('.kts')) return 'java'
  if (lower.endsWith('.rs')) return 'rust'
  if (lower.endsWith('.c') || lower.endsWith('.h') || lower.endsWith('.cpp') || lower.endsWith('.hpp') || lower.endsWith('.cc')) return 'cpp'
  if (lower.endsWith('.cs')) return 'csharp'
  if (lower.endsWith('.php')) return 'php'
  if (lower.endsWith('.rb')) return 'ruby'
  if (lower.endsWith('.lua')) return 'lua'
  if (lower.endsWith('.r')) return 'r'
  if (lower.endsWith('.swift')) return 'swift'
  if (lower.endsWith('.dart')) return 'dart'
  if (lower.endsWith('.vue')) return 'html'
  if (lower.endsWith('.md') || lower.endsWith('.markdown') || lower.endsWith('.mdx')) return 'markdown'
  if (lower.endsWith('.graphql') || lower.endsWith('.gql') || lower.endsWith('.graphqls')) return 'graphql'
  if (lower.endsWith('.proto')) return 'protobuf'
  return 'plaintext'
}
